### ISSUE TITLE
Scanner - Address for Sparkfun Qwiic buttons

### ISSUE THREAD

**Issue by KurtE** [PaulStoffregen/Wire#19]
@PaulStoffregen (@defragster, @mjs513)

Not sure if best to ask these type questions here or in email... 

As part of Wire testing, I am now playing with Sparkfun Qwiic button.  Ones like:
https://www.sparkfun.com/products/15932

Currently if you run scanner it will say 0x6f as unknown chip. 
In our modified version of scanner that search all three possible Wire busses I added in case:
```
    case 0x6F: Serial.print(F("Qwiic_BTN")); break;
```
Which for my case (default is fine), but this device has 4 address solder jumpers (all open with PU), 
So default is 0x6f, but can have any of 0x60-0x6f.

Simple question is should all of them be added?  If s, I could easily do PR... or... 

Thanks

**Comment by PaulStoffregen** [comment]
Done
https://github.com/PaulStoffregen/Wire/commit/6ec2a5a10a5b87c75a9054e1fa62db4299495668
